FROM baseimage

WORKDIR /src

COPY ./django/stockpicker/stockpicker /src/stockpicker
COPY ./django/stockpicker/tickers /src/tickers
COPY ./django/stockpicker/manage.py /src/manage.py
COPY ./django/stockpicker/stockpicker/settings/container_settings.py /src/stockpicker/settings/local_settings.py