Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 8000, host: 8080

  config.vm.provision :shell, path: "bootstrap.sh"

  config.vm.synced_folder "./../", "/home/ubuntu/devops-toolkit"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
    v.name = "Ubuntu18"
  end

end